### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by Arin-Torney** [IshanKuber/Code-Editor#1]
# Issue  
You told that you will fix some bugs in it later, so I have found a bug and also how can you fix it. First of all see your part of code for the bug is there
```HTML
    <div class="editor" contenteditable="true" title="Code Editor">
      <hr />
      <span class="line"
        >01|<br />
        02|<br />
        03|<br />
        04|<br />
        05|<br />
        06|<br />
        07|<br />
        08|<br />
        09|<br />
        10|<br />
        11|<br />
        12|<br />
        13|<br />
        14|<br />
        15|<br />
        16|<br />
        17|<br />
        18|<br />
        19|<br />
        20|<br />
        21|<br />
        22|<br />
        23|<br />
        24|<br />
        25|<br />
        26|<br />
        27|<br />
        28|<br />
        29|<br />
        30|</span
      >
      <hr />
    </div>```

**Comment by Arin-Torney** [comment]
Here you see that you wrote the whole div as `contentEditable=true`. Here is the actual bug. It makes those numbers erasable. So it causes inconvenience. So you can do a thing. Make a table and then put only the right side of it contenteditable. The left column of it should only contain the numbers and that "|". Here if you are bored of putting contenteditable as true on the whole right side of the table just use JavaScript HTML DOM. This is one way to fix the bug yet it has some bugs too. But it is at least better than that snippett. I think if you want to remove all the bugs you can use some advanced level JavaScript.

**Comment by IshanKuber** [comment]
Thank you for your suggestion
I will surely take this into consideration

**Comment by Arin-Torney** [comment]
Welcome
